version: "3.8"
services:
  serve_static:
    container_name: maintanence_page
    image: nginx:alpine
    volumes:
      - "./:/usr/share/nginx/html/"
    ports:
      - "8080:80"
    restart: always
